# Generated by Django 4.2 on 2024-11-29 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_alumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Email must be in the format lnnnnnn@lhr.nu.edu.pk', regex='^l\\d{6}@lhr\\.nu\\.edu\\.pk$')]),
        ),
    ]
