# Generated by Django 4.2 on 2024-11-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_alter_alumni_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/files/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assignments/images/'),
        ),
    ]
