# Generated by Django 4.2 on 2024-12-02 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_quizz'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pastPaper/images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='pastPaper/files/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastPaper', to='comments.course')),
            ],
        ),
    ]
