# Generated by Django 4.2 on 2024-12-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0014_alter_assignment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='description',
            field=models.TextField(blank=True, default='No Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='description',
            field=models.TextField(blank=True, default='No Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizz',
            name='description',
            field=models.TextField(blank=True, default='No Description'),
            preserve_default=False,
        ),
    ]
